---
title: "Análisis: Sensación de (in)justicia en las notas"
author: Equipo EDUMER
subtitle: SoJ
fontsize: 12pt
#bibliography: "../input/mini-proyecto.bib"
#csl: "input/bib/apa6.csl"
format:
  html:
    toc: true
    toc-location: right
    toc-depth: 6
    toc-expand: 6
    toc-title: Contenidos
    number-sections: false
    number-depth: 6
    theme: 
    - edumer.scss
    - sandstone
    title-block-banner: true
editor: visual
lang: es
---

```{r, data, echo=FALSE}
pacman::p_load(dplyr, sjmisc, car, sjlabelled, stargazer, haven, sjPlot, ggplot2, tidyr, stringr, corrplot)

load("../input/data/proc/ola1.RData")

```

```{r, select, echo=FALSE}
datos <- proc_datos %>% select(notas_esfuerzo, notas_merit,
                               justicia_nota, justicia_nota_ch, 
                               justicia_nota_tiempo_ch,
                               genero_ES,
                               libros_hogar, curso_estudiante,
                               educ_max, school_esfuerzo_ES, 
                               school_talento_ES,
                               school_merito_ES, 
                               merit_esfuerzo_percep_ES, 
                               merit_talento_percep_ES,
                               social_merito_percep_ES, 
                               rendimiento
                               )


```

# Ola 1

## [Descriptivos univariados]{.black}

```{r, echo=FALSE}
print(summarytools::dfSummary(datos), method="render")
```

<br/>

## Descriptivos bivariados

### Matriz

```{r, echo=FALSE}
#datos$notas_esfuerzo <- as.factor(datos$notas_esfuerzo)
datos$notas_merit <- as.factor(datos$notas_merit)
datos$curso_estudiante <- as.factor(datos$curso_estudiante)
datos$curso_estudiante <- as.numeric(datos$curso_estudiante)
datos$school_esfuerzo_ES <- as.factor(datos$school_esfuerzo_ES)
datos$school_talento_ES <- as.factor(datos$school_talento_ES)
datos$school_merito_ES <- as.factor(datos$school_merito_ES)
datos$merit_esfuerzo_percep_ES <- as.factor(datos$merit_esfuerzo_percep_ES)
datos$merit_talento_percep_ES <- as.factor(datos$merit_talento_percep_ES)
datos$social_merito_percep_ES <- as.factor(datos$social_merito_percep_ES)


proc_datos <- datos %>% select(justicia_nota, 
                           genero_ES,
                               libros_hogar,
        curso_estudiante,
                               educ_max, 
                           school_esfuerzo_ES, 
                               school_talento_ES,
                               school_merito_ES, 
                               merit_esfuerzo_percep_ES, 
                               merit_talento_percep_ES,
                               social_merito_percep_ES, 
                               rendimiento)  %>% na.omit() %>%
  mutate_all(~(as.numeric(.)))  



#matriz
sjPlot::tab_corr(proc_datos, 
                 triangle = "lower")

#grafico sociodem
cormat <- proc_datos %>% select(justicia_nota, 
                           genero_ES,
                               libros_hogar,
                           curso_estudiante,
                               educ_max
                           ) %>% cor(.)

corrplot(cormat,
method = 'color',
  type = 'upper',
  #number.cex = 3,
  #tl.cex = 3,
  diag = FALSE,
addCoef.col = "black",
tl.col = "black")

# grafico merit
cor_mat <- proc_datos %>% select(justicia_nota, 
                           school_esfuerzo_ES, 
                               school_talento_ES,
                               school_merito_ES, 
                               merit_esfuerzo_percep_ES, 
                               merit_talento_percep_ES,
                               social_merito_percep_ES) %>% cor(.)

corrplot(cor_mat,
method = 'color',
  type = 'upper',
  #number.cex = 3,
  #tl.cex = 3,
  diag = FALSE,
addCoef.col = "black",
tl.col = "black")
```

#### Diferencias por género

```{r, echo=FALSE, warning=FALSE}
test_just_g <- t.test(proc_datos$justicia_nota ~ proc_datos$genero_ES, 
                   alternative = "greater",
                   conf.level = 0.95)

test_just_g
gginference::ggttest(test_just_g)
```

#### Diferencias por curso

```{r, echo=FALSE, warning=FALSE}
test_just_c <- t.test(proc_datos$justicia_nota ~ proc_datos$curso_estudiante, 
                   alternative = "greater",
                   conf.level = 0.95)

test_just_c
gginference::ggttest(test_just_c)
```

#### Diferencias por cantidad de libros en el hogar

```{r, echo=FALSE, warning=FALSE}
test_just_l <- t.test(proc_datos$justicia_nota ~ proc_datos$libros_hogar, 
                   alternative = "greater",
                   conf.level = 0.95)

test_just_l
gginference::ggttest(test_just_l)
```

#### Diferencias por educación máxima de los padres

```{r, echo=FALSE, warning=FALSE}
test_just_e <- t.test(proc_datos$justicia_nota ~ proc_datos$educ_max, 
                   alternative = "greater",
                   conf.level = 0.95)

test_just_e
gginference::ggttest(test_just_e)
```

## Modelos

### Modelos simples

```{r}
r1 <- lm(justicia_nota~ genero_ES , data = proc_datos)
r2 <- lm(justicia_nota~ curso_estudiante , data = proc_datos)
r3 <- lm(justicia_nota~ libros_hogar , data = proc_datos)
r4 <- lm(justicia_nota~ educ_max , data = proc_datos)
r5 <- lm(justicia_nota~ merit_esfuerzo_percep_ES , data = proc_datos)
r6 <- lm(justicia_nota~ merit_talento_percep_ES , data = proc_datos)
r7 <- lm(justicia_nota~ school_esfuerzo_ES , data = proc_datos)
r8 <- lm(justicia_nota~ school_talento_ES , data = proc_datos)
r9 <- lm(justicia_nota~ school_merito_ES , data = proc_datos)
r10 <- lm(justicia_nota~ rendimiento , data = proc_datos)

sjPlot::tab_model(list(r1, r2,r3, r4,r5, r6, r7, r8, r9, r10), show.ci=FALSE, p.style = "stars", dv.labels = c("Modelo 1", "Modelo 2", "Modelo 3", "Modelo 4", "Modelo 5", "Modelo 6", "Modelo 7", "Modelo 8", "Modelo 9", "Modelo 10" ),string.pred = "Predictores", string.est = "β")
```


### Modelo regresión lineal múltiple

```{r, echo=FALSE}
modelo1 <- lm(justicia_nota ~ genero_ES + curso_estudiante, data = proc_datos)
modelo2 <- lm(justicia_nota ~  genero_ES + curso_estudiante + educ_max , data = proc_datos)
modelo3 <- lm(justicia_nota ~ genero_ES + curso_estudiante + educ_max + libros_hogar, data = proc_datos)
modelo4 <- lm(justicia_nota ~ genero_ES + curso_estudiante + educ_max + libros_hogar + merit_esfuerzo_percep_ES, data = proc_datos)
modelo5 <- lm(justicia_nota ~ genero_ES + curso_estudiante + educ_max + libros_hogar + merit_esfuerzo_percep_ES + merit_talento_percep_ES, data = proc_datos)
modelo6 <- lm(justicia_nota ~ genero_ES + curso_estudiante + educ_max + libros_hogar + merit_esfuerzo_percep_ES + merit_talento_percep_ES + school_merito_ES, data = proc_datos)
modelo7 <- lm(justicia_nota ~ genero_ES + curso_estudiante + educ_max + libros_hogar + merit_esfuerzo_percep_ES + merit_talento_percep_ES + school_merito_ES + school_esfuerzo_ES, data = proc_datos)
modelo8 <- lm(justicia_nota ~ genero_ES + curso_estudiante + educ_max + libros_hogar + merit_esfuerzo_percep_ES + merit_talento_percep_ES + school_merito_ES + school_esfuerzo_ES + school_talento_ES, data = proc_datos)
modelo9 <- lm(justicia_nota ~ genero_ES + curso_estudiante + educ_max + libros_hogar + merit_esfuerzo_percep_ES + merit_talento_percep_ES + school_merito_ES + school_esfuerzo_ES + school_talento_ES + rendimiento, data = proc_datos)


sjPlot::tab_model(list(modelo1, modelo2,modelo3, modelo4,modelo5, modelo6, modelo7, modelo8, modelo9), show.ci=FALSE, p.style = "stars", dv.labels = c("Modelo 1", "Modelo 2", "Modelo 3", "Modelo 4", "Modelo 5", "Modelo 6", "Modelo 7", "Modelo 8", "Modelo 9" ),string.pred = "Predictores", string.est = "β")

#plot(modelo5, which = 1)  # Residuals vs Fitted plot

plot_model(modelo9, show.values = TRUE)+ theme_sjplot()


```

# Ola 2

```{r}
load("../input/data/proc/proc_w02.RData")
```

## Bivariados

```{r}
proc_datos_o2 <- datos %>% select(justicia_nota, 
                           genero,
                               libros_hogar,
                           curso,
                               educ_max, 
                           school_esfuerzo, 
                               school_talento,
                               school_merecimiento, 
                               merit_esfuerzo, 
                               merit_talento,
                                
                               nota)  %>% na.omit() %>%
  mutate_all(~(as.numeric(.)))  

#matriz
sjPlot::tab_corr(proc_datos_o2, 
                 triangle = "lower")
```

### Modelos simples

```{r}
reg1 <- lm(justicia_nota~ genero , data = proc_datos_o2)
reg2 <- lm(justicia_nota~ curso , data = proc_datos_o2)
reg3 <- lm(justicia_nota~ libros_hogar , data = proc_datos_o2)
reg4 <- lm(justicia_nota~ educ_max , data = proc_datos_o2)
reg5 <- lm(justicia_nota~ merit_esfuerzo , data = proc_datos_o2)
reg6 <- lm(justicia_nota~ merit_talento , data = proc_datos_o2)
reg7 <- lm(justicia_nota~ school_esfuerzo , data = proc_datos_o2)
reg8 <- lm(justicia_nota~ school_talento , data = proc_datos_o2)
reg9 <- lm(justicia_nota~ school_merecimiento , data = proc_datos_o2)
reg10 <- lm(justicia_nota~ nota , data = proc_datos_o2)

sjPlot::tab_model(list(reg1, reg2,reg3, reg4,reg5, reg6, reg7, reg8, reg9, reg10), show.ci=FALSE, p.style = "stars", dv.labels = c("Modelo 1", "Modelo 2", "Modelo 3", "Modelo 4", "Modelo 5", "Modelo 6", "Modelo 7", "Modelo 8", "Modelo 9", "Modelo 10" ),string.pred = "Predictores", string.est = "β")
```



### Modelos múltiples
```{r}
modelo1 <- lm(justicia_nota ~ genero + curso, data = proc_datos_o2)
modelo2 <- lm(justicia_nota ~  genero + curso + educ_max , data = proc_datos_o2)
modelo3 <- lm(justicia_nota ~ genero + curso + educ_max + libros_hogar, data = proc_datos_o2)
modelo4 <- lm(justicia_nota ~ genero + curso + educ_max + libros_hogar + merit_esfuerzo, data = proc_datos_o2)
modelo5 <- lm(justicia_nota ~ genero + curso + educ_max + libros_hogar + merit_esfuerzo + merit_talento, data = proc_datos_o2)
modelo6 <- lm(justicia_nota ~ genero + curso + educ_max + libros_hogar + merit_esfuerzo + merit_talento + school_merecimiento, data = proc_datos_o2)
modelo7 <- lm(justicia_nota ~ genero + curso + educ_max + libros_hogar  + merit_esfuerzo + merit_talento + school_merecimiento + school_esfuerzo, data = proc_datos_o2)
modelo8 <- lm(justicia_nota ~ genero + curso + educ_max + libros_hogar + merit_esfuerzo + merit_talento + school_merecimiento + school_esfuerzo + school_talento, data = proc_datos_o2)
modelo9 <- lm(justicia_nota ~ genero + curso + educ_max + libros_hogar + merit_esfuerzo + merit_talento + school_merecimiento + school_esfuerzo + school_talento + nota, data = proc_datos_o2)


sjPlot::tab_model(list(modelo1, modelo2,modelo3, modelo4,modelo5, modelo6, modelo7, modelo8, modelo9), show.ci=FALSE, p.style = "stars", dv.labels = c("Modelo 1", "Modelo 2", "Modelo 3", "Modelo 4", "Modelo 5", "Modelo 6", "Modelo 7", "Modelo 8", "Modelo 9" ),string.pred = "Predictores", string.est = "β")

#plot(modelo5, which = 1)  # Residuals vs Fitted plot

plot_model(modelo9, show.values = TRUE)+ theme_sjplot()



```

